const mongoose = require('mongoose');

const OnlineAdmissionSchema = new mongoose.Schema({
  admission_no: { type: String },
  roll_no: { type: String },
  reference_no: { type: String, required: true },
  admission_date: { type: Date },
  firstname: { type: String, required: true },
  middlename: { type: String },
  lastname: { type: String },
  rte: { type: String, default: 'No' },
  image: { type: String },
  mobileno: { type: String },
  email: { type: String },
  state: { type: String },
  city: { type: String },
  pincode: { type: String },
  religion: { type: String },
  caste: { type: String },
  dob: { type: Date },
  gender: { type: String },
  category_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Category' },
  class_section_id: { type: mongoose.Schema.Types.ObjectId, ref: 'ClassSection' },
  school_house_id: { type: mongoose.Schema.Types.ObjectId, ref: 'SchoolHouse' },
  blood_group: { type: String },
  vehroute_id: { type: mongoose.Schema.Types.ObjectId, ref: 'VehicleRoute' },
  hostel_room_id: { type: mongoose.Schema.Types.ObjectId, ref: 'HostelRoom' },
  adhar_no: { type: String },
  samagra_id: { type: String },
  bank_account_no: { type: String },
  bank_name: { type: String },
  ifsc_code: { type: String },
  guardian_is: { type: String },
  father_name: { type: String },
  father_phone: { type: String },
  father_occupation: { type: String },
  mother_name: { type: String },
  mother_phone: { type: String },
  mother_occupation: { type: String },
  guardian_name: { type: String },
  guardian_phone: { type: String },
  guardian_occupation: { type: String },
  guardian_email: { type: String },
  current_address: { type: String },
  permanent_address: { type: String },
  upload_documents: [{ type: String }],
  status: { type: String, default: 'pending' }, // pending, approved, rejected
  payment_status: { type: String, default: 'unpaid' }, // unpaid, paid
  custom_fields: { type: Object },
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now }
});

module.exports = mongoose.model('OnlineAdmission', OnlineAdmissionSchema);
