const mongoose = require('mongoose');

const SettingSchema = new mongoose.Schema({
  lastname: String,
  middlename: String,
  name: String,
  email: String,
  phone: String,
  address: String,
  timezone: String,
  date_format: String,
  currency: { type: mongoose.Schema.Types.ObjectId, ref: 'Currency' },
  currency_place: String,
  lang_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Language' },
  languages: String,
  class_teacher: String,
  session_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Session' },
  fee_due_days: Number,
  image: String,
  theme: String,
  online_admission: Boolean,
  is_duplicate_fees_invoice: Boolean,
  is_student_house: Boolean,
  is_blood_group: Boolean,
  admin_logo: String,
  admin_small_logo: String,
  mobile_api_url: String,
  app_primary_color_code: String,
  app_secondary_color_code: String,
  app_logo: String,
  student_profile_edit: Boolean,
  staff_barcode: Boolean,
  student_barcode: Boolean,
  student_panel_login: Boolean,
  parent_panel_login: Boolean,
  currency_format: String,
  exam_result: Boolean,
  base_url: String,
  folder_path: String,
  admin_login_page_background: String,
  user_login_page_background: String,
  low_attendance_limit: Number,
  saas_key: String,
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Setting', SettingSchema);
