const mongoose = require('mongoose');

const StudentSchema = new mongoose.Schema({
  admission_no: { type: String, required: true, unique: true },
  roll_no: { type: String },
  admission_date: { type: Date },
  firstname: { type: String, required: true },
  middlename: { type: String },
  lastname: { type: String },
  image: { type: String },
  mobileno: { type: String },
  email: { type: String },
  state: { type: String },
  city: { type: String },
  pincode: { type: String },
  religion: { type: String },
  dob: { type: Date },
  current_address: { type: String },
  permanent_address: { type: String },
  category_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Category' },
  category: { type: String },
  adhar_no: { type: String },
  samagra_id: { type: String },
  bank_account_no: { type: String },
  bank_name: { type: String },
  ifsc_code: { type: String },
  guardian_name: { type: String },
  guardian_relation: { type: String },
  guardian_email: { type: String },
  guardian_phone: { type: String },
  guardian_address: { type: String },
  is_active: { type: Boolean, default: true },
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now },
  father_name: { type: String },
  rte: { type: String },
  gender: { type: String },
  app_key: { type: String },
  parent_app_key: { type: String },
  father_phone: { type: String },
  father_occupation: { type: String },
  mother_name: { type: String },
  mother_phone: { type: String },
  mother_occupation: { type: String },
  guardian_occupation: { type: String },
  guardian_is: { type: String },
  note: { type: String },
  previous_school: { type: String },
  height: { type: String },
  weight: { type: String },
  measurement_date: { type: Date },
  blood_group: { type: String },
  school_house_id: { type: mongoose.Schema.Types.ObjectId, ref: 'SchoolHouse' },
  father_pic: { type: String },
  mother_pic: { type: String },
  guardian_pic: { type: String },
  dis_reason: { type: String },
  dis_note: { type: String },
  disable_at: { type: Date },
  hostel_room_id: { type: mongoose.Schema.Types.ObjectId, ref: 'HostelRoom' },
  parent_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Parent' },
  class_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Class' },
  section_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Section' },
  session_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Session' },
  user_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
});

module.exports = mongoose.model('Student', StudentSchema);
